const Transaction = require("../models/Transaction");

/**
 * Synchronizes session data by identifying "stale" transactions
 * (where payee details have changed) and invalidating their embeddings.
 *
 * The background embeddingJob.js (runs every 60s) will pick up
 * transactions with null embeddings and regenerate them.
 *
 * Summary regeneration is NOT needed here — the analytics page and
 * AI tools now use live aggregations that always read the latest
 * payee categories from the database.
 *
 * @param {string} sessionId - The session ID to sync.
 * @returns {Promise<{ updatedTransactions: number, updatedSummaries: number }>}
 */
async function syncSessionData(sessionId) {
  console.log(`[syncService] Starting sync for session: ${sessionId}`);

  // 1. Find all transactions with a payee for this session
  const transactions = await Transaction.find({
    sessionId,
    payee: { $exists: true },
  }).populate("payee");

  // 2. Filter for stale transactions
  // Stale if:
  // - Payee category != embeddingMetadata category OR
  // - Payee displayName != embeddingMetadata merchant
  const staleTransactions = transactions.filter((tx) => {
    if (!tx.payee) return false;

    const currentCategory = tx.payee.category;
    const currentMerchant = tx.payee.displayName;

    const storedCategory = tx.embeddingMetadata?.category;
    const storedMerchant = tx.embeddingMetadata?.merchant;

    return currentCategory !== storedCategory || currentMerchant !== storedMerchant;
  });

  if (staleTransactions.length === 0) {
    console.log("[syncService] No stale transactions found.");
    return { updatedTransactions: 0, updatedSummaries: 0 };
  }

  console.log(`[syncService] Found ${staleTransactions.length} stale transactions. Invalidating embeddings.`);

  // 3. Invalidate embeddings in chunks of 50
  const chunkSize = 50;
  let totalUpdated = 0;

  for (let i = 0; i < staleTransactions.length; i += chunkSize) {
    const chunk = staleTransactions.slice(i, i + chunkSize);

    const bulkOps = chunk.map((tx) => ({
      updateOne: {
        filter: { _id: tx._id },
        update: {
          $set: {
            embedding: null, // will be regenerated by embeddingJob
            embeddingMetadata: {
              merchant: tx.payee.displayName,
              category: tx.payee.category,
            },
          },
        },
      },
    }));

    const result = await Transaction.bulkWrite(bulkOps);
    totalUpdated += result.modifiedCount || 0;
  }

  console.log(`[syncService] Invalidated ${totalUpdated} embeddings. Background job will regenerate them.`);

  return {
    updatedTransactions: totalUpdated,
    updatedSummaries: 0, // summaries are now live — nothing to regenerate
  };
}

module.exports = { syncSessionData };
